platform :ios, '7.0'

pod 'Reachability', '~> 3.2'
pod 'AFNetworking', '~> 2.6.1'
pod 'MJRefresh', '~> 2.2.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJExtension', '~> 2.5.12'
pod 'FDFullscreenPopGesture', '1.1'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'CYLTabBarController', '~> 1.2.7'
pod 'JASidePanels', '~> 1.3.2'
pod 'Braintree', '~> 3.9'
pod 'Braintree/Data', '~> 3.9'
